apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: rbactest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep1
  namespace: rbactest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep2
  namespace: rbactest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podsecuritypolicy
  namespace: rbactest
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - system
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podsecuritypolicy
  namespace: rbactest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podsecuritypolicy
subjects:
- kind: ServiceAccount
  name: default
  namespace: rbactest
- kind: ServiceAccount
  name: sleep1
  namespace: rbactest
- kind: ServiceAccount
  name: sleep2
  namespace: rbactest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep1
  namespace: rbactest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep1
    spec:
      serviceAccountName: sleep1
      containers:
      - name: sleep1
        image: pstauffer/curl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep2
  namespace: rbactest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep2
    spec:
      serviceAccountName: sleep2
      containers:
      - name: sleep2
        image: pstauffer/curl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    system/mesh-upstream: "true"
  namespace: rbactest
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
  namespace: rbactest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
