apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: mtls-test
    namespace: rbactest
spec:
    host: "*.rbactest.svc.cluster.local"
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
