apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nacos
  labels:
    app: nacos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - image: nacos/nacos-server:1.1.0
        imagePullPolicy: IfNotPresent
        name: nacos
        env:
        - name: MODE
          value: standalone
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nacos
  name: nacos
spec:
  ports:
  - name: http-8848
    port: 8848
    targetPort: 8848
    nodePort: 30848
  type: NodePort
  selector:
    app: nacos
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: producer
        imagePullPolicy: IfNotPresent
        name: producer
        command:
          - "/wait-for-it.sh"
          - "nacos:8848"
          - "--"
          - "java"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-jar"
          - "/app.jar"
        env:
        - name: REGISTRY_PROTOCOL
          value: nacos
        - name: REGISTRY_SERVER
          value: nacos
        - name: REGISTRY_PORT
          value: "8848"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: consumer
        imagePullPolicy: IfNotPresent
        name: consumer
        command:
          - "/wait-for-it.sh"
          - "nacos:8848"
          - "--"
          - "java"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-jar"
          - "/app.jar"
        env:
        - name: REGISTRY_PROTOCOL
          value: nacos
        - name: REGISTRY_SERVER
          value: nacos
        - name: REGISTRY_PORT
          value: "8848"
        - name: SERVER_PORT
          value: "8899"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  ports:
  - name: http-8899
    port: 8899
    targetPort: 8899
    nodePort: 30899
  type: NodePort
  selector:
    app: consumer
