apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: registry.aliyuncs.com/acs-sample/zookeeper:3.4.8
        imagePullPolicy: IfNotPresent
        name: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  ports:
  - name: http-2181
    port: 2181
    targetPort: 2181
    nodePort: 30181
  type: NodePort
  selector:
    app: zookeeper
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: producer
        imagePullPolicy: IfNotPresent
        name: producer
        command:
          - "/wait-for-it.sh"
          - "zookeeper:2181"
          - "--"
          - "java"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-jar"
          - "/app.jar"
        env:
        - name: REGISTRY_PROTOCOL
          value: zookeeper
        - name: REGISTRY_SERVER
          value: zookeeper
        - name: REGISTRY_PORT
          value: "2181"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: consumer
        imagePullPolicy: IfNotPresent
        name: consumer
        command:
          - "/wait-for-it.sh"
          - "zookeeper:2181"
          - "--"
          - "java"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-jar"
          - "/app.jar"
        env:
        - name: REGISTRY_PROTOCOL
          value: zookeeper
        - name: REGISTRY_SERVER
          value: zookeeper
        - name: REGISTRY_PORT
          value: "2181"
        - name: SERVER_PORT
          value: "8899"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  ports:
  - name: http-8899
    port: 8899
    targetPort: 8899
    nodePort: 30899
  type: NodePort
  selector:
    app: consumer
