version: "2"
services:
  zookeeper:
    image: 'registry.aliyuncs.com/acs-sample/zookeeper:3.4.8'
    hostname: zookeeper
  producer:
    image: 'producer:latest'
    environment:
      - REGISTRY_PROTOCOL=zookeeper
      - REGISTRY_SERVER=zookeeper
      - REGISTRY_PORT=2181
    depends_on:
      - zookeeper
    command: ["./wait-for-it.sh", "zookeeper:2181", "--", "java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  consumer:
    image: 'consumer:latest'
    environment:
      - REGISTRY_PROTOCOL=zookeeper
      - REGISTRY_SERVER=zookeeper
      - REGISTRY_PORT=2181
      - SERVER_PORT=8899
    depends_on:
      - zookeeper
    command: ["./wait-for-it.sh", "zookeeper:2181", "--", "java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8899:8899
