apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: rbactest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer
  namespace: rbactest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podsecuritypolicy
  namespace: rbactest
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - system
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podsecuritypolicy
  namespace: rbactest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podsecuritypolicy
subjects:
- kind: ServiceAccount
  name: default
  namespace: rbactest
- kind: ServiceAccount
  name: consumer
  namespace: rbactest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nacos
  namespace: rbactest
  labels:
    app: nacos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - image: nacos/nacos-server:1.1.0
        imagePullPolicy: IfNotPresent
        name: nacos
        ports:
        - containerPort: 8848
        env:
        - name: MODE
          value: standalone
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nacos
    system/mesh-upstream: "true"
  name: nacos
  namespace: rbactest
spec:
  ports:
  - name: http-8848
    port: 8848
    targetPort: 8848
  selector:
    app: nacos
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: producer
  namespace: rbactest
  labels:
    app: producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
        version: v1
    spec:
      containers:
      - image: shouhong001/producer:ip-from-env
        imagePullPolicy: IfNotPresent
        name: producer
        command:
          - "/wait-for-it.sh"
          - "nacos:8848"
          - "--"
          - "java"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-jar"
          - "/app.jar"
        ports:
        - containerPort: 20880
        env:
        - name: VERSION
          value: V1
        - name: REGISTRY_PROTOCOL
          value: nacos
        - name: REGISTRY_SERVER
          value: nacos
        - name: REGISTRY_PORT
          value: "8848"
---
apiVersion: v1
kind: Service
metadata:
  annotations: 
    servicetype: dubbo
  labels:
    app: producer
    system/mesh-upstream: "true"
  name: producer
  namespace: rbactest
spec:
  ports:
  - name: x-dubbo-port
    protocol: TCP
    port: 20880
    targetPort: 20880
  selector:
    app: producer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer
  namespace: rbactest
  labels:
    app: consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      serviceAccountName: consumer
      containers:
      - image: shouhong001/consumer
        imagePullPolicy: IfNotPresent
        name: consumer
        command:
          - "/wait-for-it.sh"
          - "nacos:8848"
          - "--"
          - "java"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-jar"
          - "/app.jar"
        ports:
        - containerPort: 8899
        env:
        - name: PROVIDER_CLUSER_IP
          value: producer
        - name: REGISTRY_PROTOCOL
          value: nacos
        - name: REGISTRY_SERVER
          value: nacos
        - name: REGISTRY_PORT
          value: "8848"
        - name: SERVER_PORT
          value: "8899"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
    system/mesh-upstream: "true"
  name: consumer
  namespace: rbactest
spec:
  ports:
  - name: http-8899
    port: 8899
    targetPort: 8899
  selector:
    app: consumer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
  namespace: rbactest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: dustise/sleep
          imagePullPolicy: IfNotPresent
