apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: rbactest
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: mtls-test
    namespace: rbactest
spec:
    host: "*.rbactest.svc.cluster.local"
    trafficPolicy:
      tls:
        mode: DISABLE
