apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: producer
  namespace: rbactest
spec:
  rules:
  - services:
    - producer.rbactest.svc.cluster.local
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: producer
  namespace: rbactest
spec:
  subjects:
  - names:
    - "spiffe://cluster.local/ns/rbactest/sa/consumer"
  roleRef:
    kind: ServiceRole
    name: producer
